version: "3.8"

services:
  mongo-db:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"

  todo-server:
    build: ./server
    ports:
      - "3001:3001"
    depends_on:
      - mongo-db
